### ISSUE TITLE
Integrate coverage module for Amundsen repositories

### ISSUE THREAD

**Issue by verdan** [lyft/amundsenmetadatalibrary#17]

**Comment by feng-tao** [comment]
@verdan , feel free to create a pr for this issue :)

**Comment by verdan** [comment]
@feng-tao I believe this needs to be done with the admin rights of repo. 
Admin needs to add this repo to codecov to generate the token, and that will be used in the CI server. 

https://docs.codecov.io/docs

**Comment by feng-tao** [comment]
@verdan , let me do that.

**Comment by jornh** [comment]
Seems this was resolved a while ago:

* https://github.com/lyft/amundsenmetadatalibrary/pull/64#issuecomment-511990833
* https://github.com/lyft/amundsenfrontendlibrary/pull/230#issuecomment-513002273
* https://github.com/lyft/amundsensearchlibrary/pull/39#issuecomment-512598426
* https://github.com/lyft/amundsendatabuilder/pull/114#issuecomment-512588068
