### ISSUE TITLE
docker pull amundsen-metadata : repository does not exist

### ISSUE THREAD

**Issue by ashitabh** [lyft/amundsenmetadatalibrary#20]
I am not able to get this working via docker
getting following error
pull access denied for amundsen-metadata, repository does not exist or may require 'docker login'

**Comment by feng-tao** [comment]
@ashitabh , we haven't push the repo to docker hub. Currently we need to clone the repo and run https://github.com/lyft/amundsenmetadatalibrary/blob/master/public.Dockerfile. We will update the readme to be more clear :)

**Comment by rosejcday** [comment]
On that same container, has anyone else seen this error where it says npm not found and issues with "no files found matching ..." when running the command `docker build -f public.Dockerfile -t amundsen-metadata:latest .`

```
Step 5/7 : RUN python3 setup.py install
 ---> Running in 291cf382651d
/bin/sh: 1: npm: not found
ERROR:root:npm must be available
/bin/sh: 1: npm: not found
setup.py:27: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
  logging.warn('Installation of npm dependencies failed')
WARNING:root:Installation of npm dependencies failed
setup.py:28: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
  logging.warn(str(e))
WARNING:root:Command '['npm install']' returned non-zero exit status 127.
running install
running bdist_egg
running egg_info
writing amundsen_frontend.egg-info/PKG-INFO
writing dependency_links to amundsen_frontend.egg-info/dependency_links.txt
writing entry points to amundsen_frontend.egg-info/entry_points.txt
writing requirements to amundsen_frontend.egg-info/requires.txt
writing top-level names to amundsen_frontend.egg-info/top_level.txt
reading manifest file 'amundsen_frontend.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'amundsen_application/static/dist'
warning: no files found matching '*' under directory 'amundsen_application/.*/static/dist'
warning: no files found matching '*' under directory 'amundsen_application/.*/static/fonts'
warning: no files found matching '*' under directory 'amundsen_application/.*/static/images'
writing manifest file 'amundsen_frontend.egg-info/SOURCES.txt'
```

I also saw this zip_safe flag warning: 

```
zip_safe flag not set; analyzing archive contents...
amundsen_application.__pycache__.__init__.cpython-37: module references __file__
```

**Comment by feng-tao** [comment]
@rosejcday not sure why it shows NPM missing, but metadata doesn't include any NPM package. So I assume the warning is safe to ignore.

**Comment by feng-tao** [comment]
@rosejcday , @ashitabh I just published all 3 Amundsen repos images to dockerhub. Now you could take a at this pr(https://github.com/lyft/amundsenfrontendlibrary/pull/115).

**Comment by rosejcday** [comment]
@feng-tao thanks! I will use those now.

**Comment by jornh** [comment]
@feng-tao  and ... 

> @rosejcday not sure why it shows NPM missing, but metadata doesn't include any NPM package. So I assume the warning is safe to ignore.

I think I have spotted why that error appears in the run above. Somewhere in the output there’s a reference to `amundsen_frontend` which *does* depend on npm for building. So it’s safe to ignore in the context of this Amundsen Metadata repo - though still a bug. 😉 I’ll open an issue (or PR) in that other frontend repo.

**Comment by feng-tao** [comment]
thanks @jornh
