### ISSUE TITLE
Make amundsen compatible with upcoming release of Atlas i.e., v2.0

### ISSUE THREAD

**Issue by verdan** [lyft/amundsenmetadatalibrary#32]
Atlas is working on new release, which might break our implementation of Amundsen Atlas proxy. Make sure atlas's 1.1x+ versions are supported by amundsen. Keep backward compatibility in mind while implementing this.

**Comment by verdan** [comment]
One of the breaking change is that the new version of Atlas does not include `relationshipAttributes` under `attribute` key anymore.

**Comment by jinhyukchang** [comment]
@verdan Just reviewed the PR, merged and released it. Let me know if you need anything. Thanks!

**Comment by verdan** [comment]
thanks @jinhyukchang. this can be closed for now :)
