### ISSUE TITLE
need sample data

### ISSUE THREAD

**Issue by user919lx** [lyft/amundsenmetadatalibrary#57]
I want to display column stats like this ![colstats](https://cdn-images-1.medium.com/max/1600/1*HDifsST0l5HAnt13qOR_XA.png)
But I don't know what data model in neo4j is. Though can get some info from neo4j_proxy's cypher query, I still need complete model.

Sample data can help me understand data model and then I can import data by myself.

**Comment by feng-tao** [comment]
@user919lx do you store column stat somewhere? The data model is https://github.com/lyft/amundsendatabuilder/blob/master/databuilder/models/table_stats.py . 

I am pretty packed this two week. But will find some time to write sample data after that.

**Comment by user919lx** [comment]
Thanks.
I am lost in so many models in these projects. 
Now I can try to import data by myself.
