### ISSUE TITLE
Decouple Neo4j from amundsen project

### ISSUE THREAD

**Issue by verdan** [lyft/amundsenmetadatalibrary#7]
The idea is to use Apache Atlas for the metadata and search for amundsen. 
In order to use the Amundsen project with other services/databases we should make the proxy integrations generic enough (probably using factory pattern) to introduce any new service easily. 
At the moment, the metadeta and search service are tightly coupled with Neo4j.

**Comment by jinhyukchang** [comment]
@verdan Sounds good and let us know if you face any issue or discuss on direction.
By the way, I am not sure search service is coupled with Neo4j as it does not aware of Neo4j.

**Comment by jinhyukchang** [comment]
@verdan FYI, we have several plugin example in place where we use Python's entry point.

https://github.com/lyft/amundsenfrontendlibrary/blob/master/amundsen_application/log/action_log_callback.py#L85
https://github.com/lyft/amundsenfrontendlibrary/blob/master/setup.py#L63

**Comment by verdan** [comment]
this is our intended architecture of amundsen that we want to use within our team. @feng-tao @jinhyukchang 
![Amundsen_DAP_Goal](https://user-images.githubusercontent.com/25360476/54237205-b7b17180-4515-11e9-8197-66258ffaa87a.png)

**Comment by feng-tao** [comment]
great @verdan , I think it makes sense.

**Comment by jinhyukchang** [comment]
@verdan Looks good to me. As you already noticed, search svc also has proxy layer and I think it can follow the same pattern as metadata service using Atlas proxy.

**Comment by verdan** [comment]
@jinhyukchang the search service proxy is using elasticsearch, which can be pointed directly to Atlas's elasticsearch instead of going via Atlas itself, or I am missing something here?

**Comment by jinhyukchang** [comment]
@verdan Yep, I understood that would be the way that you are heading to. It's just the architecture diagram above put proxy layer on metadata service but not on search service.

**Comment by verdan** [comment]
this can be closed now I believe

**Comment by feng-tao** [comment]
yes @verdan
